feat: 후보자 검색 기능 구현
NullFull/call22nd pull request #12
Opened 2024-03-06 07:12 UTC by nestiank

웹페이지 하단의 후보자 검색 기능을 [call21st](https://github.com/NullFull/call21st) 쪽의 구현을 가져와서 구현합니다.

- 제21대 후보자 json 파일을 탑재하여 테스트가 가능하도록 했습니다. 이 파일들은 추후 교체합니다.
  - [x] 지역구: 선거구로 검색 잘 됨
  - [x] 비례대표: 정당으로 검색 잘 됨
  - [x] 후보자 이름으로 검색 잘 됨
- DB 연결은 향후 작업합니다.

2024-03-06 12:58 UTC, koremp commented on package-lock.json
yarn 또는 npm 하나만 사용하는 것이 좋을 것 같습니다.

2024-03-06 13:01 UTC, koremp requested changes
yarn.lock 을 처음부터 써왔기 때문에 yarn.lock을 남기고 package-lock.json 을 지우는 것이 좋겠습니다.

2024-03-06 13:09 UTC, nestiank commented on package-lock.json
1. 다른 리뷰할 내용은 없으신가요?
2. 어느 쪽이 좋을까요..?

2024-03-06 13:11 UTC, koremp commented on package-lock.json
1. 없습니다.
2. 제 취향은 yarn 이긴 한데 이전까지 yarn.lock을 사용했으니까 yarn 쓰는게 좋지 않을까요?

2024-03-07 10:54 UTC, koremp approved these changes

2024-03-07 11:10 UTC, nestiank commented
대신 작업 감사드립니다!

2024-03-07 11:10 UTC, merged