페이지에서 보이는 부분 작성
NullFull/call22nd pull request #5
Opened 2024-02-23 10:46 UTC by nestiank

보이는 부분을 거의 다 작성했습니다.
- 아래쪽 투명 버튼 2개에 아이콘을 넣어야 합니다.
- 핵심 기능 부분은 컴포넌트만 빼 두었습니다.

2024-02-23 10:51 UTC, koremp reviewed
main에 min-width: 360px 가 들어가면 좋을  것 같습니다.

2024-02-24 10:15 UTC, koremp requested changes
1차 리뷰

2024-02-24 10:15 UTC, koremp commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
이런 text 부분들을 따로 json 파일들로 모아놓거나 하는 것이 더 좋을 수도 있겠다는 생각이 드네요 (개인적인 의견)

2024-02-24 10:15 UTC, koremp commented on src/app/main.css
> +.main {
`max-width: 360px;`
를 추가하면 많이 깨지네요 ;( 이건 좀 봐야 할 것 같네요. vw 대신에 px 사용 부탁드려요.

2024-02-24 10:15 UTC, koremp commented on src/components/WhiteButton.tsx
> +      <Link href={props.link}>
외부 링크로 빠져나갈 때 필요한 이모지나 사진이 필요한 것 같습니당

2024-02-24 10:15 UTC, koremp commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
현재 p 태그 안에 문장을 모두 넣었는데, 문장의 가독성을 높이기 위해서 디자인 시안처럼 문장을 끊기 위해 br 태그도 같이 넣는 것이 좋을 것 같아요.

2024-02-24 10:15 UTC, koremp reviewed
1차 리뷰

2024-02-24 10:17 UTC, nestiank commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
json 부분은 당장은 잘 모르겠고, br 태그 사용은... keep-all을 넣었기 때문에 br 태그 사용하지 않았습니다. 단말기 width 차이에 따라 우리가 임의로 끊은 한 줄이 두 줄로 보일 가능성이 있어서요.

2024-02-24 10:19 UTC, nestiank commented on src/app/main.css
> +.main {
모바일 디바이스 간 width 차이 때문에 vw로 했습니다. `max-width: 360px` 넣어서 확인해 보겠습니다.

2024-02-24 10:19 UTC, nestiank commented on src/components/WhiteButton.tsx
> +      <Link href={props.link}>
아래쪽 투명 버튼 2개에 아이콘이 빠진 걸 말씀하시는 거죠? 넣겠습니다.

2024-02-24 10:23 UTC, nestiank commented on src/app/main.css
> +.main {
혹시 `max-width: 360px` 어디에 넣으셨을까요? CSS에서 `.main` 쪽에 넣었을 때는 깨지지 않는 것 같습니다.

2024-02-24 10:32 UTC, nestiank commented on src/components/WhiteButton.tsx
> +      <Link href={props.link}>
넣어 두었습니다~

2024-02-24 12:41 UTC, koremp commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
그건 채널에서 논의해봐야 할 것 같네용

2024-02-24 12:41 UTC, koremp commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
그러면 우리가 사용한 `<br>` 태그 대신 끊은 각각의 문단을 `<p>`태그를 사용하고 `flex`를 사용하여 보이게 하는 것이 좋을 것 같네용

2024-02-24 12:43 UTC, koremp commented on src/app/main.css
> +.main {
저희 모바일 먼저 개발하는데 반응형으로 개발하나요? 그게 확실치 않아서 채널에 물어봐야 할 것 같아요.

2024-02-26 05:18 UTC, nestiank commented on src/app/main.css
> +.main {
그러고 보니 반응형으로 한다고 하면 media tag 넣어서 일정 크기 이상으로는 커지지 않게 하는 게 좋을 것 같네요.

2024-02-26 05:26 UTC, nestiank commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
우리의 textarea에 `display: flex` 넣을 이유는 잘 모르겠어요. 넘치는 경우가 문제라면 그냥 `overflow-wrap: break-word` 추가하면 되지 않을까 싶은데요.

2024-02-26 12:41 UTC, koremp approved these changes

2024-02-26 12:45 UTC, koremp commented
위로 올라가기 버튼 만드는 것을 노션의 주영님 일감에 추가했고 `ScrollToTop` 버튼을 만드시면 될 것 같습니다. 다만 `develop` 브랜치에 이런 개발사항을 한꺼번에 올리는 것이 좋을지 논의해봐야 할 것 같네요. 저희 `feat/basic`, `feat/scrollToTop`, `feat/linkButtons` 등으로 브랜치 네이밍이나 커밋 컨벤션까지 지킬지 고민해보는 것이 좋을 것 같습니다.

2024-02-26 12:48 UTC, koremp commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
넘치는 것보다 가독성 문제라고 생각해요.
`콜 22팀이 여러분의 질문을 대신 전해드립니다` 라는 문장을 보았을 때

```md
콜 22팀이 여러분의
질문을 대신
전해드립니다.
```

보다

```md
콜 22팀이 여러분의 질문을
대신 전해드립니다
```

식으로 보이는 것이 가독성이 좋지 않을까 싶습니다.

2024-02-26 12:50 UTC, koremp commented on src/app/main.css
> +.main {
다만 빠른 프로토타이핑을 한다고 하면 저희가 반응형이 아닌 fixed width 를 최소로 정해놓고 나머지 width를 빈칸으로 설정하는 것도 방법이어서 media tag까지 가야하나 싶긴 하네요. 물론 디테일을 살리고 인력이 많고 실력이 충분하면 가능할 것 같기는 해요.

2024-02-26 12:50 UTC, koremp requested changes
저희 일단 모바일 반응형인지 콜22 채널 참여자분들의 결정을 여쭤봐야할 . 것같습니다.

2024-02-26 23:55 UTC, nestiank commented on src/app/main.css
> +.main {
말씀하신 내용 참고해서 테스트해 본 결과 그냥 viewport width 360px 기준으로 vw를 전부 px로 바꿨어요. 그래도 이쁘게 잘 나오고 반응형이더라고요.

2024-02-26 23:56 UTC, nestiank commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
지금 코드도 "콜 22팀이 여러분의 질문을" 이게 화면 width에 따라 한 줄에 다 들어가면 한 줄로 나오지 않나요? 화면 width가 작아서 "콜 22팀이 여러분의" 까지만 들어가면 잘릴 수밖에 없지 않나 싶어서요. 제가 뭔가 놓치고 있을까요?

2024-02-26 23:58 UTC, nestiank commented
브랜치 네이밍은 앞으로는 말씀하신 대로 하는 게 좋을 것 같고요, `scrollToTop` 버튼은 다음 PR 때 추가하겠습니다. 일단 방금 수정의 결과로 현재 반응형이긴 합니다.

2024-02-27 06:30 UTC, nestiank commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
디스코드로 얘기 나누었습니다. 피그마에 있는 대로 br 태그 넣어서 문단 끊어짐을 viewport width와 관계 없게 하기로 했습니다.

2024-02-27 10:01 UTC, nestiank commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
처리하였으니 리뷰 부탁드립니다.

2024-02-27 10:11 UTC, koremp commented on src/app/page.tsx
> +        <p>우리 동네<br />국회의원 후보자들에게<br />강간죄를 개정할 뜻이 있는지<br />물어봐 주세요.</p>
```
우리 동네 국회의원
후보자들에게
```

2024-02-27 10:31 UTC, koremp reviewed
그라데이션이 반대로 되어있습니다

2024-02-27 10:33 UTC, koremp commented on src/app/page.tsx
> +        <p>우리 동네<br />국회의원 후보자들에게<br />강간죄를 개정할 뜻이 있는지<br />물어봐 주세요.</p>
```
우리 동네 지역
국회의원 후보자들에게
```

가 좀 더 좋을 것 같은데 피그마에 문구 수정여부를 달아야 할까요?

2024-02-27 10:37 UTC, koremp commented on src/app/page.tsx
> +        <p>우리 동네 국회의원 후보자들은 불평등한 강간죄를 바꿔 볼 생각이 있는 걸까?</p>
리뷰 확인해주세용

2024-02-27 10:42 UTC, nestiank commented on src/app/page.tsx
> +        <p>우리 동네<br />국회의원 후보자들에게<br />강간죄를 개정할 뜻이 있는지<br />물어봐 주세요.</p>
저도 그래서 말씀하신 후자로 했는데요, "동네"와 "지역"이 동어반복인 것 같아서 "지역"을 뺐습니다.

2024-02-27 10:43 UTC, koremp commented
시안과
![image](https://github.com/NullFull/call22nd/assets/18482476/71667aae-3dce-4ff3-89dd-7a90004f20e0)

현재 개발화면
![image](https://github.com/NullFull/call22nd/assets/18482476/4b467a0e-78ca-4e5c-9925-49353829cf9b)

과 맞지 않는 부분이 있어요
반짝이는 부분이 꼭 필요한 것은 아닌 것 같기는 한데 그래도 요구사항대로 맞춰볼까요?

2024-02-27 10:43 UTC, koremp commented
마찬가지로 이전 시안은 이랬는데
![image](https://github.com/NullFull/call22nd/assets/18482476/510bedd1-4dab-4773-97d1-b16847fb7de3)

현재 시안은 이래서
![image](https://github.com/NullFull/call22nd/assets/18482476/78197d33-421d-4108-83e8-29e6a5d9945a)

이건 바꿔야 할 것 같아요

2024-02-27 10:44 UTC, koremp commented
> 그라데이션이 반대로 되어있습니다

이건 제가 옛날 코드로 봤네요... 지금 잘 되어있습니다

2024-02-27 10:45 UTC, koremp commented
별 아이콘이 들어간 링크 컴포넌트가 있고 빠진 것이 있어서 그거 확인을 해봐야 할 것 같습니다

2024-02-27 10:47 UTC, koremp commented on src/app/page.tsx
> +        <p>우리 동네<br />국회의원 후보자들에게<br />강간죄를 개정할 뜻이 있는지<br />물어봐 주세요.</p>
그렇네요 위쪽 텍스트는
`우리 동네 국회의원이라고 적혀있고`
아래는
`...동네 지역...`
이라고  되어있네요
동어 반복하지 않아도 될 것 같습니당 👍🏼

2024-02-27 10:49 UTC, nestiank commented
> 별 아이콘이 들어간 링크 컴포넌트가 있고 빠진 것이 있어서 그거 확인을 해봐야 할 것 같습니다

별 아이콘 중에 링크가 걸린 부분이 있나요? 아니면 종 근처에 별 아이콘 빠진 것을 말씀하시는 건가요?

2024-02-27 10:50 UTC, koremp commented
아래 판결/기사 보기 border 크기가 4px인데 2로 줄여야 할 것 같아요

2024-02-27 10:51 UTC, koremp commented
> > 별 아이콘이 들어간 링크 컴포넌트가 있고 빠진 것이 있어서 그거 확인을 해봐야 할 것 같습니다
> 
> 별 아이콘 중에 링크가 걸린 부분이 있나요? 아니면 종 근처에 별 아이콘 빠진 것을 말씀하시는 건가요?

첫번째 브로슈어 다운로드에 별이 빠졌는데 아마 디자인 하신 분이 실수하신 것일 수도 있고 근데 크게 중요하지는 않을 것 같습니다

2024-02-27 10:53 UTC, nestiank commented
- 그라디언트가 위와 아래 양쪽 끝으로 있어야 하는데 한쪽으로만 되어 있어서 수정했습니다.
- 흰색 버튼 border 2px로 수정했습니다.
- 첫 번째 브로슈어에서 별이 빠진 건 디자인 실수인 것 같습니다.

다음은 수정해야 할 내용들을 정리한 것인데, 이것들만 하면 되는 게 맞는지 봐주세요!
- [ ] 종 그림 근처에 별 그림 두 개 빠진 것 넣기
- [ ] 맨 위쪽 2024와 Call 22 원의 디자인 수정 사항 반영

2024-02-27 11:03 UTC, koremp commented
> * 그라디언트가 위와 아래 양쪽 끝으로 있어야 하는데 한쪽으로만 되어 있어서 수정했습니다.
> * 흰색 버튼 border 2px로 수정했습니다.
> * 첫 번째 브로슈어에서 별이 빠진 건 디자인 실수인 것 같습니다.
> 
> 다음은 수정해야 할 내용들을 정리한 것인데, 이것들만 하면 되는 게 맞는지 봐주세요!
> 
> * [ ]  종 그림 근처에 별 그림 두 개 빠진 것 넣기
> * [ ]  맨 위쪽 2024와 Call 22 원의 디자인 수정 사항 반영
> * [ ]  scrollToUp -> 다음 PR에서 수정

네 맞습니다 이것만 되면 이번 PR은 approve 하고 머지할게요

2024-02-27 12:35 UTC, koremp commented
애쓰셨어요! 다 됐습니다.

2024-02-27 12:35 UTC, koremp approved these changes

2024-02-27 12:35 UTC, merged